[package]
name = "zip-extract"
version = "0.1.2"
authors = ["M*C*O <mcofficer@gmx.de>"]
edition = "2018"
license = "MIT"
description = "Archive extraction via zip-rs, automated."
repository = "https://github.com/MCOfficer/zip-extract"
keywords = ["zip", "archive", "extract"]
categories = ["compression"]

[features]
"deflate" = ["zip/deflate", "zip/deflate64"]
"deflate-miniz" = ["zip/deflate-miniz"]
"default-zlib" = ["zip/deflate-zlib"]
"bzip2" = ["zip/bzip2"]
"default" = ["bzip2", "deflate"]

[dependencies]
log = "0.4"
zip = { git = "https://github.com/anatawa12/zip-rs", branch = "deflate64" }
encoding_rs = "0.8"
thiserror = "1.0"

[dev-dependencies]
cute-log = { version = "2.0.7", default_features = false }
dir-diff = "0.3.2"
tempfile = "3.4.0"
